services:
  web:
      build: pdfhtmlrss_platform_web
      ports:
        - "8080:80"
      hostname:
        frontend
      networks:
        frontend:
        backend:
      depends_on:
        - api
  api:
    build:
      dockerfile: ./backend.Dockerfile
      context: ./
#        ports:
#          - 8081:8080
    hostname:
      api
    volumes:
      - pdfrsstmp:/tmp/pdfrss
      - ${HOME}/.pdfhtmlrss:/pdfhtmlrss
#        tmpfs:
#          - /tmp/pdfrss
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/pdfhtmlrss
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_GENERATE-DDL=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pdfhtmlrss2024
      - SPRING_REDIS_HOST=redisdb
      - PDFHTMLRSS_KEYSTORE_PATH=/pdfhtmlrss/keystore.jks
      - PDFHTMLRSS_KEYSTORE_PASSWORD=
    networks:
      backend:
    depends_on:
      mariadb:
          condition: service_healthy
      redisdb:
          condition: service_healthy
  redisdb :
    image: redis:latest
    restart: always
    hostname: redisdb
    networks:
      backend:
    volumes:
      - rediscache:/data
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 10s
        timeout: 5s
        retries: 3
  mariadb :
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: pdfhtmlrss
      MARIADB_ROOT_PASSWORD: pdfhtmlrss2024
    networks:
      backend:
    volumes:
      - database:/var/lib/mysql
    #https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  frontend:
    internal: false
  backend:
    driver: bridge
    internal: false
volumes:
  pdfrsstmp:
    driver: local
    driver_opts:
      type : tmpfs
      device : tmpfs
  database:
    driver: local
  rediscache:
    driver: local