#create an application-override.properties file by copying this file and populate the values
#Should be a BCrypt hashed Password
pdfhtmlrss.user.admin.password=
spring.datasource.username=
spring.datasource.password=